name: release
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
  
      - name: Install dependencies
        run: npm ci
      
      - name: Generating the site
        run: npm run docs:build

      - name: Copy files to remote server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: './docs/.vitepress/dist/*'
          target: '/home/' 