name: release
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm
        run: npm i

      - name: Add VitePress
        run: npm add -D vitepress

      - name: Build VitePress
        run: npm run docs:build

      - name: Copy files to remote server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: './docs/.vitepress/dist/*'
          target: '/home/' 